name: Bug report
description: Report a bug to help us improve
labels: [bug]
body:
  - type: textarea
    attributes:
      label: Describe the bug
      description: What happened? What did you expect?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Steps to reproduce
      value: |
        1.
        2.
        3.
    validations:
      required: true
  - type: input
    attributes:
      label: App version / build channel
  - type: textarea
    attributes:
      label: Logs / screenshots
